Repository AutoMapper/AutoMapper, pull requests merged in 2018-06, with the labels that each got.

#2641 Nullable untyped MapFrom
  src/AutoMapper/Mappers/NullableDestinationMapper.cs
  src/UnitTests/Bug/NullableUntypedMapFrom.cs
Labels: Improvement

#2651 Add a section about conditions and resolvers
  docs/Conditional-mapping.md
  docs/Custom-value-resolvers.md
  docs/Editing-Resolvers-and-Conditions.md
Labels: Documentation

#2669 Fix SetTraceIdentifierAction constructor name
  docs/Before-and-after-map-actions.md
Labels: Documentation

#2662 Fix bad similar type replacement in parameters
  src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
Labels: Improvement

#2664 Link to the new expressions package
  docs/Expression-Translation-(UseAsDataSource).md
Labels: Documentation

#2671 Include with open generics
  src/AutoMapper/AutoMapper.csproj
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/MapperConfiguration.cs
  src/AutoMapper/ProfileMap.cs
  src/AutoMapper/PropertyMap.cs
  src/AutoMapper/TypeMap.cs
  src/AutoMapper/TypePair.cs
  src/UnitTests/MappingInheritance/OpenGenericsWithInheritance.cs
Labels: Feature

#2681 ProjectTo : An edge case with the let clause
  src/AutoMapper/QueryableExtensions/Impl/NullableDestinationExpressionBinder.cs
  src/IntegrationTests/CustomMapFrom/MapObjectPropertyFromSubQuery.cs
Labels: Improvement

#2682 Remove package references to System.Reflection.Emit
  src/AutoMapper/AutoMapper.csproj
  src/AutoMapper/Execution/PropertyDescription.cs
  src/AutoMapper/Execution/PropertyEmitter.cs
  src/AutoMapper/Execution/ProxyGenerator.cs
  src/AutoMapper/Execution/TypeDescription.cs
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/LockingConcurrentDictionary.cs
  src/AutoMapper/Mapper.cs
  src/AutoMapper/Mappers/TypeConverterMapper.cs
  src/AutoMapper/PropertyMap.cs
  src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
  src/AutoMapper/TypeExtensions.cs
  src/UnitTests/AutoMapper.UnitTests.csproj
  src/UnitTests/Bug/MapAtRuntimeWithCollections/EntityDTO20.cs
  src/UnitTests/DynamicMapping.cs
  src/UnitTests/InterfaceMapping.cs
  src/UnitTests/Internal/CreateProxyThreading.cs
  src/UnitTests/Projection/ProjectionTests.cs
Labels: Internal refactoring

#2679 Adding sourcelink to enable PDB debugging
  src/AutoMapper/AutoMapper.csproj
Labels: Improvement

#2698 Implement ShouldUseConstructor
  docs/Construction.md
  src/AutoMapper/Configuration/IProfileConfiguration.cs
  src/AutoMapper/IProfileExpression.cs
  src/AutoMapper/Profile.cs
  src/AutoMapper/ProfileMap.cs
  src/AutoMapper/TypeDetails.cs
  src/AutoMapper/TypeMap.cs
  src/UnitTests/ShouldUseConstructor.cs
Labels: Feature
