Repository AutoMapper/AutoMapper, pull requests merged in 2018-09, with the labels that each got.

#2790 ProxyGenerator: The fully qualified type name must be less than 1,024 characters.
  src/AutoMapper/Execution/ProxyGenerator.cs
  src/IntegrationTests/CustomMapFrom/MapObjectPropertyFromSubQuery.cs
Labels: Improvement

#2804 Drop netstandard13
  default.ps1
  src/AutoMapper/AssemblyInfo.cs
  src/AutoMapper/AutoMapper.csproj
  src/AutoMapper/Execution/PropertyEmitter.cs
  src/AutoMapper/Execution/ProxyGenerator.cs
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/Mappers/ArrayCopyMapper.cs
  src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
  src/AutoMapper/TypeExtensions.cs
  src/Benchmark/Benchmark.csproj
  src/IntegrationTests/AutoMapper.IntegrationTests.csproj
  src/UnitTests/AutoMapper.UnitTests.csproj
  src/UnitTests/DynamicMapping.cs
  src/UnitTests/InterfaceMapping.cs
  src/UnitTests/Internal/CreateProxyThreading.cs
  src/UnitTests/Internal/GenerateSimilarType.cs
  src/UnitTests/Internal/NullConstructorParameter.cs
  src/UnitTests/TypeConverters.cs
Labels: Internal refactoring

#2800 fixed whitespace
  src/AutoMapper/TypeExtensions.cs
Labels: Internal refactoring

#2806 Value converters
  default.ps1
  docs/Dependency-injection.md
  docs/Value-converters.md
  docs/index.rst
  src/AutoMapper/Configuration/MappingExpression.cs
  src/AutoMapper/Configuration/MemberConfigurationExpression.cs
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/IMemberConfigurationExpression.cs
  src/AutoMapper/IValueConverter.cs
  src/AutoMapper/PropertyMap.cs
  src/AutoMapper/ValueConverterConfiguration.cs
  src/UnitTests/ValueConverters.cs
Labels: Feature

#2808 Consolidate construct using
  AutoMapper.sln
  docs/8.0-Upgrade-Guide.md
  src/AutoMapper/Configuration/MappingExpression.cs
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/IMappingExpression.cs
  src/AutoMapper/TypeMap.cs
  src/IntegrationTests/MaxDepth/NestedDtos.cs
  src/UnitTests/IMappingExpression/NonGenericConstructorTests.cs
  src/UnitTests/Projection/ConstructorTests.cs
Labels: Improvement

#2810 Consider ForPath when checking for cycles
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/UnitTests/BidirectionalRelationshipsWithoutPR.cs
Labels: Improvement
