Repository AutoMapper/AutoMapper, pull requests merged in 2018-11, with the labels that each got.

#2846 ForPath works only with Map
  docs/Queryable-Extensions.md
Labels: Documentation

#2849 Validate closed generic maps
  src/AutoMapper/ConfigurationValidator.cs
  src/AutoMapper/Mapper.cs
  src/AutoMapper/MapperConfiguration.cs
  src/AutoMapper/ProfileMap.cs
  src/AutoMapper/PropertyMap.cs
  src/AutoMapper/TypeMap.cs
  src/UnitTests/Bug/UseDestinationValue.cs
  src/UnitTests/InterfaceMapping.cs
  src/UnitTests/OpenGenerics.cs
Labels: Improvement

#2850 Added example for Castle Windsor
  docs/Dependency-injection.md
Labels: Documentation

#2859 Generic maps validation
  docs/8.0-Upgrade-Guide.md
Labels: Documentation

#2867 Update Dependency-injection.md
  docs/Dependency-injection.md
Labels: Documentation

#2873 Read only dictionaries support
  src/AutoMapper/Configuration/Internal/PrimitiveHelper.cs
  src/AutoMapper/Configuration/PrimitiveExtensions.cs
  src/AutoMapper/Execution/DelegateFactory.cs
  src/AutoMapper/Mappers/Internal/ElementTypeHelper.cs
  src/AutoMapper/Mappers/MapperRegistry.cs
  src/AutoMapper/Mappers/ReadOnlyCollectionMapper.cs
  src/AutoMapper/Mappers/ReadOnlyDictionaryMapper.cs
  src/UnitTests/Mappers/ReadOnlyCollectionMapperTests.cs
  src/UnitTests/Mappers/ReadOnlyDictionaryMapperTests.cs
Labels: Feature

#2876 Update Static-and-Instance-API.md
  ISSUE_TEMPLATE.md
  docs/Static-and-Instance-API.md
Labels: Documentation

#2878 Update Value-converters.md
  docs/Value-converters.md
Labels: Documentation

#2887 A constructor parameter with no name won't match anything
  src/AutoMapper/ReflectionExtensions.cs
  src/AutoMapper/TypeMapFactory.cs
  src/UnitTests/Bug/NullConstructorParameterName.cs
Labels: Bug

#2901 A value converter/resolver always returns a value of the destination …
  src/AutoMapper/ConfigurationValidator.cs
  src/UnitTests/ConfigurationValidation.cs
Labels: Bug
