Repository AutoMapper/AutoMapper, pull requests merged in 2018-08, with the labels that each got.

#2751 System.ValueTuple is included from 4.7 on
  src/AutoMapper/AutoMapper.csproj
Labels: Internal refactoring

#2741 fix PropertiesWithAnInaccessibleSetter
  src/AutoMapper/TypeExtensions.cs
  src/UnitTests/IgnoreAllPropertiesWithAnInaccessibleSetterTests.cs
Labels: Bug

#2746 Check for generic instances of included maps
  src/AutoMapper/IConfigurationProvider.cs
  src/AutoMapper/MapperConfiguration.cs
  src/AutoMapper/ProfileMap.cs
  src/UnitTests/MappingInheritance/OpenGenericsWithInheritance.cs
Labels: Bug

#2778 AssertConfigurationIsValid(profileName) should throw if name does not exist
  src/AutoMapper/MapperConfiguration.cs
  src/UnitTests/ConfigurationValidation.cs
Labels: Improvement

#2774 Update Value-transformers.md
  docs/Value-transformers.md
Labels: Documentation
