Repository AutoMapper/AutoMapper, pull requests merged in 2019-01, with the labels that each got.

#2923 Use https
  CONTRIBUTING.md
  Directory.Build.props
  ISSUE_TEMPLATE.md
  README.md
  docs/5.0-Upgrade-Guide.md
  src/AutoMapper/AdvancedConfiguration.cs
  src/AutoMapper/IConfigurationProvider.cs
Labels: Documentation

#2927 Generics with untyped MapFrom
  src/AutoMapper/PropertyMap.cs
  src/UnitTests/OpenGenerics.cs
Labels: Bug

#2928 Set UseDestinationValue for readonly members
  src/AutoMapper/Configuration/MemberConfigurationExpression.cs
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/PropertyMap.cs
  src/UnitTests/CollectionMapping.cs
Labels: Improvement

#2935 Update index.rst
  docs/index.rst
Labels: Documentation

#2933 Attributes to define a type map configuration
  src/AutoMapper/AutoMapAttribute.cs
  src/AutoMapper/Configuration/CtorParamConfigurationExpression.cs
  src/AutoMapper/Configuration/ICtorParameterConfiguration.cs
  src/AutoMapper/Configuration/ISourceMemberConfiguration.cs
  src/AutoMapper/Configuration/MapperConfigurationExpression.cs
  src/AutoMapper/Configuration/MappingExpression.cs
  src/AutoMapper/Configuration/MappingExpressionBase.cs
  src/AutoMapper/Configuration/MemberConfigurationExpression.cs
  src/AutoMapper/Configuration/SourceMappingExpression.cs
  src/AutoMapper/ICtorParamConfigurationExpression.cs
  src/AutoMapper/IMapperConfigurationExpression.cs
  src/AutoMapper/IMappingExpression.cs
  src/AutoMapper/IMappingExpressionBase.cs
  src/UnitTests/AssemblyScanning.cs
  src/UnitTests/AttributeBasedMaps.cs
Labels: Feature

#2938 Assume single automap attribute
  src/AutoMapper/Configuration/MapperConfigurationExpression.cs
Labels: Internal refactoring

#2940 Flow resolution context to nested mappings
  Directory.Build.props
  src/AutoMapper/ResolutionContext.cs
  src/UnitTests/ContextItems.cs
Labels: Improvement

#2950 We pass the destination member, not the source member
  src/AutoMapper/IMemberConfigurationExpression.cs
Labels: Documentation

#2952 Added AddProfiles method that takes an IEnumerable<Profile>
  src/AutoMapper/Configuration/MapperConfigurationExpression.cs
  src/AutoMapper/IMapperConfigurationExpression.cs
  src/UnitTests/AddProfiles.cs
Labels: Improvement

#2960 Add support to specify ShouldMapMethod
  src/AutoMapper/Configuration/IProfileConfiguration.cs
  src/AutoMapper/IProfileExpression.cs
  src/AutoMapper/Profile.cs
  src/AutoMapper/ProfileMap.cs
  src/AutoMapper/TypeDetails.cs
  src/UnitTests/ShouldMapMethod.cs
Labels: Improvement
