Repository AutoMapper/AutoMapper, pull requests merged in 2019-12, with the labels that each got.

#3271 Update index.rst
  docs/index.rst
Labels: Documentation

#3268 Honour AllowNullDestinationValues
  src/AutoMapper/ApiCompatBaseline.txt
  src/AutoMapper/Configuration/PrimitiveExtensions.cs
  src/AutoMapper/Execution/DelegateFactory.cs
  src/AutoMapper/Execution/ExpressionBuilder.cs
  src/AutoMapper/TypeDetails.cs
  src/UnitTests/Bug/AllowNullDestinationValuesBugs.cs
Labels: Bug

#3274 Enabled custom validation for TypeConverters via Advanced.Validator
  src/AutoMapper/ConfigurationValidator.cs
  src/UnitTests/ConfigurationValidation.cs
  src/UnitTests/CustomValidations.cs
Labels: Improvement

#3279 Typo
  docs/Conditional-mapping.md
Labels: Documentation

#3284 Removed dead links in Exception class
  src/AutoMapper/AutoMapperMappingException.cs
Labels: Documentation
