Repository AutoMapper/AutoMapper, pull requests merged in 2019-04, with the labels that each got.

#3021 Checking collections for null is not allowed in EF6
  src/AutoMapper/QueryableExtensions/Impl/MappedTypeExpressionBinder.cs
  src/IntegrationTests/NullCheckCollections.cs
Labels: Bug

#3020 fixed enum values caseinsensitivity bug
  src/AutoMapper/Mappers/EnumToEnumMapper.cs
  src/UnitTests/Bug/EnumCaseSensitivityBug.cs
Labels: Bug

#3014 IncludeMembers docs
  CONTRIBUTING.md
  docs/Flattening.md
  docs/Mapping-inheritance.md
  docs/Migrating-from-static-API.md
  docs/Reverse-Mapping-and-Unflattening.md
  docs/The-MyGet-build.md
  docs/index.rst
Labels: Documentation

#3041 Refactor feature extensions
  src/AutoMapper/Configuration/MapperConfigurationExpression.cs
  src/AutoMapper/Configuration/MappingExpressionBase.cs
  src/AutoMapper/Configuration/PrimitiveExtensions.cs
  src/AutoMapper/Features/FeatureExtensions.cs
  src/AutoMapper/Features/Features.cs
  src/AutoMapper/Features/GlobalFeatures.cs
  src/AutoMapper/Features/IRuntimeFeature.cs
  src/AutoMapper/Features/MappingFeatures.cs
  src/AutoMapper/Features/RuntimeFeatures.cs
  src/AutoMapper/IConfigurationProvider.cs
  src/AutoMapper/IMapperConfigurationExpression.cs
  src/AutoMapper/IMappingExpressionBase.cs
  src/AutoMapper/MapperConfiguration.cs
  src/AutoMapper/TypeMap.cs
  src/UnitTests/ConfigurationFeatureTest.cs
  src/UnitTests/MappingExpressionFeatureWithReverseTest.cs
  src/UnitTests/MappingExpressionFeatureWithoutReverseTest.cs
Labels: Internal refactoring

#3040 Match members by name
  src/AutoMapper/Configuration/MappingExpression.cs
  src/AutoMapper/Configuration/MappingExpressionBase.cs
  src/UnitTests/ForAllOtherMembers.cs
Labels: Bug

#3034 Update Mapping-inheritance.md
  docs/Flattening.md
  docs/Mapping-inheritance.md
Labels: Documentation

#3048 Adding new docs for mapping attributes
  docs/Attribute-mapping.md
  docs/Configuration.md
  docs/index.rst
Labels: Documentation
