Repository AutoMapper/AutoMapper, pull requests merged in 2019-08, with the labels that each got.

#3182 Help the runtime find the AM assembly
  src/UnitTests/AssemblyScanning.cs
Labels: Improvement

#3173 Don't check for IDisposable at runtime for value types
  src/AutoMapper/Internal/ExpressionFactory.cs
  src/UnitTests/CollectionMapping.cs
Labels: Improvement

#3172 Allow non nullable default values for nullable enum constructor param…
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/UnitTests/Constructors.cs
Labels: Bug

#3180 Update Custom-value-resolvers.md
  docs/Custom-value-resolvers.md
  docs/Dependency-injection.md
Labels: Documentation

#3187 Match destination enumerable types with it's enumerable for LINQ
  src/AutoMapper/QueryableExtensions/Impl/EnumerableExpressionBinder.cs
  src/IntegrationTests/IEnumerableMemberProjections.cs
Labels: Improvement

#3202 Naming conventions
  .editorconfig
  AutoMapper.sln
  docs/Dependency-injection.md
  docs/Queryable-Extensions.md
  src/AutoMapper/ApiCompatBaseline.txt
  src/AutoMapper/AutoMapper.csproj
Labels: Internal refactoring
