Repository AutoMapper/AutoMapper, pull requests merged in 2019-06, with the labels that each got.

#3102 Deprecate CreateMissingTypeMaps
  src/AutoMapper/IMapperConfigurationExpression.cs
  src/AutoMapper/ProfileMap.cs
  src/IntegrationTests/AutoMapper.IntegrationTests.csproj
  src/IntegrationTests/CustomMapFrom/MapObjectPropertyFromSubQuery.cs
  src/IntegrationTests/ICollectionAggregateProjections.cs
  src/IntegrationTests/IEnumerableAggregateProjections.cs
  src/UnitTests/AutoMapper.UnitTests.csproj
  src/UnitTests/BidirectionalRelationships.cs
  src/UnitTests/BidirectionalRelationshipsWithoutPR.cs
  src/UnitTests/Bug/CannotMapICollectionToAggregateSumDestination.cs
  src/UnitTests/Bug/CannotProjectIEnumerableToAggregateDestinations.cs
  src/UnitTests/Bug/SamePropertyNameOnParentAndChildClasses.cs
  src/UnitTests/CollectionMapping.cs
  src/UnitTests/ConfigurationValidation.cs
  src/UnitTests/Constructors.cs
  src/UnitTests/ConvensionTest.cs
  src/UnitTests/ConversionOperators.cs
  src/UnitTests/DynamicMapping.cs
  src/UnitTests/Enumerations.cs
  src/UnitTests/FillingExistingDestination.cs
  src/UnitTests/IMappingExpression/ForCtorParam.cs
  src/UnitTests/IMappingExpression/IncludeMembers.cs
  src/UnitTests/Mappers/DynamicMapperTests.cs
  src/UnitTests/Mappers/NameValueCollectionMapperTests.cs
  src/UnitTests/Mappers/StringDictionaryMapperTests.cs
  src/UnitTests/MappingExpressionFeatureWithoutReverseTest.cs
  src/UnitTests/StaticMapping.cs
  src/UnitTests/TypeConverters.cs
  src/UnitTests/ValueConverters.cs
Labels: Improvement

#3123 Use the type the expression would return
  src/AutoMapper/ConstructorParameterMap.cs
  src/UnitTests/ConfigurationValidation.cs
Labels: Bug

#3124 The link is no longer valid
  docs/Getting-started.md
Labels: Documentation

#3120 Detect breaking changes
  AutoMapper.sln
  nuget.config
  src/AutoMapper/ApiCompatBaseline.txt
  src/AutoMapper/AutoMapper.csproj
  src/AutoMapper/LastMajorVersionBinary/AutoMapper.dll
Labels: Improvement

#3106 Adding ResolutionContext to IMappingAction<TSource, TDestination>.Process()
  src/AutoMapper/Configuration/MappingExpressionBase.cs
  src/AutoMapper/IMappingAction.cs
  src/UnitTests/BeforeAfterMapping.cs
Labels: Feature

#3127 Respect AllowNullCollections
  src/AutoMapper/ApiCompatBaseline.txt
  src/AutoMapper/Mapper.cs
  src/UnitTests/NullBehavior.cs
Labels: Improvement

#3136 Removing static API
  src/AutoMapper/ApiCompatBaseline.txt
  src/AutoMapper/Mapper.cs
  src/AutoMapper/QueryableExtensions/Extensions.cs
  src/UnitTests/StaticMapping.cs
Labels: Improvement

#3134 Remove dynamic maps
  src/AutoMapper/ApiCompatBaseline.txt
  src/AutoMapper/AutoMapperConfigurationException.cs
  src/AutoMapper/Configuration/IProfileConfiguration.cs
  src/AutoMapper/Configuration/MapperConfigurationExpression.cs
  src/AutoMapper/ConfigurationValidator.cs
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/IConfigurationProvider.cs
  src/AutoMapper/IMapperConfigurationExpression.cs
  src/AutoMapper/IMappingOperationOptions.cs
  src/AutoMapper/IProfileExpression.cs
  src/AutoMapper/Mapper.cs
  src/AutoMapper/MapperConfiguration.cs
  src/AutoMapper/Mappers/CreateMapBasedOnCriteriaMapper.cs
  src/AutoMapper/MappingOperationOptions.cs
  src/AutoMapper/Profile.cs
  src/AutoMapper/ProfileMap.cs
  src/AutoMapper/QueryableExtensions/Impl/QueryMapperHelper.cs
  src/AutoMapper/TypeMap.cs
  src/AutoMapper/TypePair.cs
  src/IntegrationTests/CustomMapFrom/MapObjectPropertyFromSubQuery.cs
  src/IntegrationTests/ICollectionAggregateProjections.cs
  src/IntegrationTests/IEnumerableAggregateProjections.cs
  src/UnitTests/AttributeBasedMaps.cs
  src/UnitTests/BidirectionalRelationships.cs
  src/UnitTests/BidirectionalRelationshipsWithoutPR.cs
  src/UnitTests/Bug/CannotMapICollectionToAggregateSumDestination.cs
  src/UnitTests/Bug/CannotProjectIEnumerableToAggregateDestinations.cs
  src/UnitTests/Bug/ConventionCreateMapsWithCircularReference.cs
  src/UnitTests/Bug/DestinationCtorCalledTwice.cs
  src/UnitTests/Bug/DynamicMapArrays.cs
  src/UnitTests/Bug/GenericCreateMapWithCircularReferences.cs
  src/UnitTests/Bug/MissingMapping.cs
  src/UnitTests/Bug/MultiThreadingIssues.cs
  src/UnitTests/Bug/NullableToInvalid.cs
  src/UnitTests/Bug/SamePropertyNameOnParentAndChildClasses.cs
  src/UnitTests/CollectionMapping.cs
  src/UnitTests/ConfigurationValidation.cs
  src/UnitTests/Constructors.cs
  src/UnitTests/ConvensionTest.cs
  src/UnitTests/ConversionOperators.cs
  src/UnitTests/DynamicMapping.cs
  src/UnitTests/Enumerations.cs
  src/UnitTests/FillingExistingDestination.cs
  src/UnitTests/IMappingExpression/ForCtorParam.cs
  src/UnitTests/IMappingExpression/IncludeMembers.cs
  src/UnitTests/MapToAttributeTest.cs
  src/UnitTests/Mappers/DynamicMapperTests.cs
  src/UnitTests/Mappers/NameValueCollectionMapperTests.cs
  src/UnitTests/Mappers/StringDictionaryMapperTests.cs
  src/UnitTests/MappingExpressionFeatureWithoutReverseTest.cs
  src/UnitTests/Projection/ProjectTest.cs
  src/UnitTests/ReverseMapping.cs
  src/UnitTests/TypeConverters.cs
  src/UnitTests/ValueConverters.cs
Labels: Improvement

#3141 Moving enums after assignable to simplify assignable enums
  src/AutoMapper/Mappers/MapperRegistry.cs
Labels: Internal refactoring

#3142 Docs update for 9.0
  docs/5.0-Upgrade-Guide.md
  docs/9.0-Upgrade-Guide.md
  docs/Before-and-after-map-actions.md
  docs/Conditional-mapping.md
  docs/Configuration-validation.md
  docs/Configuration.md
  docs/Construction.md
  docs/Conventions.md
  docs/Custom-type-converters.md
  docs/Custom-value-resolvers.md
  docs/Dependency-injection.md
  docs/Dynamic-and-ExpandoObject-Mapping.md
  docs/Expression-Translation-(UseAsDataSource).md
  docs/Flattening.md
  docs/Getting-started.md
  docs/Inline-Mapping.md
  docs/Lists-and-arrays.md
  docs/Mapping-inheritance.md
  docs/Open-Generics.md
  docs/Projection.md
  docs/Queryable-Extensions.md
  docs/Reverse-Mapping-and-Unflattening.md
  docs/Setup.md
  docs/Value-converters.md
  docs/Value-transformers.md
  docs/index.rst
Labels: Documentation

#3144 Automate updating last version binary
  .gitignore
  src/AutoMapper/AutoMapper.csproj
  src/AutoMapper/LastMajorVersionBinary/AutoMapper.dll
  src/AutoMapper/PreBuild.ps1
Labels: Internal refactoring

#3150 When using the context, check that the right Map overload was used
  src/AutoMapper/ResolutionContext.cs
  src/UnitTests/ContextItems.cs
Labels: Improvement

#3149 Public Source property for ContextCacheKey
  src/AutoMapper/ResolutionContext.cs
Labels: Improvement
