Repository AutoMapper/AutoMapper, pull requests merged in 2019-02, with the labels that each got.

#2969 Consolidate ProjectTo parameters handling
  src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
  src/AutoMapper/QueryableExtensions/IProjectionExpression.cs
  src/AutoMapper/QueryableExtensions/ProjectionExpression.cs
  src/UnitTests/Projection/MapFromTest.cs
Labels: Internal refactoring

#2974 Update Queryable-Extensions.md
  docs/Queryable-Extensions.md
Labels: Documentation

#2977 Skip generic mappings when precompiling
  src/AutoMapper/MapperConfiguration.cs
  src/UnitTests/ConfigCompilation.cs
Labels: Bug

#2978 AutoMap attribute configuration options
  src/AutoMapper/AutoMapAttribute.cs
  src/UnitTests/AttributeBasedMaps.cs
Labels: Improvement

#2996 Link to ASP.NET Core configuration setup
  docs/Getting-started.md
Labels: Documentation

#2995 Include a brief ASP.NET Core Example
  docs/Dependency-injection.md
Labels: Documentation

#2994 Update Dependency-injection.md
  docs/Dependency-injection.md
Labels: Documentation

#2972 Include members
  src/AutoMapper/Configuration/IPropertyMapConfiguration.cs
  src/AutoMapper/Configuration/MapperConfigurationExpression.cs
  src/AutoMapper/Configuration/MappingExpression.cs
  src/AutoMapper/Configuration/MappingExpressionBase.cs
  src/AutoMapper/Configuration/MemberConfigurationExpression.cs
  src/AutoMapper/Configuration/MemberPath.cs
  src/AutoMapper/Configuration/PathConfigurationExpression.cs
  src/AutoMapper/ConstructorParameterMap.cs
  src/AutoMapper/DefaultMemberMap.cs
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/ExpressionExtensions.cs
  src/AutoMapper/IMappingExpression.cs
  src/AutoMapper/IMappingExpressionBase.cs
  src/AutoMapper/IMemberMap.cs
  src/AutoMapper/MapperConfiguration.cs
  src/AutoMapper/PathMap.cs
  src/AutoMapper/ProfileMap.cs
  src/AutoMapper/PropertyMap.cs
  src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
  src/AutoMapper/TypeMap.cs
  src/AutoMapper/TypePair.cs
  src/IntegrationTests/IncludeMembers.cs
  src/UnitTests/AssemblyScanning.cs
  src/UnitTests/AutoMapper.UnitTests.csproj
  src/UnitTests/IMappingExpression/IncludeMembers.cs
  src/UnitTests/ReverseMapping.cs
  src/UnitTests/TypeConverters.cs
  src/UnitTests/ValueTransformers.cs
Labels: Feature

#2997 Dropping value tuples.
  src/AutoMapper/AutoMapper.csproj
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/MapperConfiguration.cs
  src/AutoMapper/ProfileMap.cs
  src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
  src/AutoMapper/TypeMap.cs
Labels: Improvement

#2981 AutoMap attribute configuration options
  src/AutoMapper/AutoMapAttribute.cs
  src/UnitTests/AttributeBasedMaps.cs
Labels: Improvement

#3001 Respect PathMappings in unmapped property names list
  src/AutoMapper/Configuration/MapperConfigurationExpression.cs
  src/AutoMapper/ConstructorParameterMap.cs
  src/AutoMapper/DefaultMemberMap.cs
  src/AutoMapper/IMemberMap.cs
  src/AutoMapper/MemberFinderVisitor.cs
  src/AutoMapper/PathMap.cs
  src/AutoMapper/PropertyMap.cs
  src/AutoMapper/TypeMap.cs
  src/UnitTests/Bug/MemberListSourceAndForPath.cs
Labels: Improvement

#3003 IncludeMembers with MemberList.Source validation
  src/AutoMapper/Configuration/MappingExpression.cs
  src/AutoMapper/Configuration/MappingExpressionBase.cs
  src/UnitTests/IMappingExpression/IncludeMembers.cs
Labels: Improvement
