Repository AutoMapper/AutoMapper, pull requests merged in 2020-09, with the labels that each got.

#3490 Ignore static constructors
  src/AutoMapper/Internal/TypeExtensions.cs
  src/UnitTests/ShouldUseConstructor.cs
Labels: Bug

#3458 Null destination value type with mapper
  .github/lock.yml
  .github/workflows/lock.yml
  ISSUE_TEMPLATE.md
  docs/Dependency-injection.md
  docs/Dynamic-and-ExpandoObject-Mapping.md
  docs/Understanding-your-mapping.md
  src/AutoMapper/ApiCompatBaseline.txt
  src/AutoMapper/Configuration/Conventions/CaseSensitiveName.cs
  src/AutoMapper/Configuration/Conventions/DefaultName.cs
  src/AutoMapper/Configuration/Conventions/ParentSourceToDestinationNameMapper.cs
  src/AutoMapper/Configuration/Conventions/PrePostfixName.cs
  src/AutoMapper/ConfigurationValidator.cs
  src/AutoMapper/DefaultMemberMap.cs
  src/AutoMapper/Execution/DelegateFactory.cs
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/IConfigurationProvider.cs
  src/AutoMapper/IMemberMap.cs
  src/AutoMapper/Internal/ExpressionFactory.cs
  src/AutoMapper/Internal/LockingConcurrentDictionary.cs
  src/AutoMapper/MapperConfiguration.cs
  src/AutoMapper/MapperConfigurationExpressionValidator.cs
  src/AutoMapper/Mappers/EnumToEnumMapper.cs
  src/AutoMapper/Mappers/FromStringDictionaryMapper.cs
  src/AutoMapper/PathMap.cs
  src/AutoMapper/ProfileMap.cs
  src/AutoMapper/PropertyMap.cs
  src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
  src/AutoMapper/QueryableExtensions/Impl/MemberResolverExpressionResultConverter.cs
  src/AutoMapper/QueryableExtensions/Impl/NullableDestinationExpressionBinder.cs
  src/AutoMapper/QueryableExtensions/Impl/QueryMapperHelper.cs
  src/AutoMapper/QueryableExtensions/NullsafeQueryRewriter.cs
  src/AutoMapper/TypeDetails.cs
  src/AutoMapper/TypeMap.cs
  src/IntegrationTests/BuiltInTypes/DateTimeToNullableDateTime.cs
  src/IntegrationTests/CustomProjection.cs
  src/IntegrationTests/ExplicitExpansion/MembersToExpandExpressions.cs
  src/IntegrationTests/ExplicitExpansion/ProjectionWithExplicitExpansion.cs
  src/IntegrationTests/IncludeMembers.cs
  src/IntegrationTests/NullCheckCollections.cs
  src/IntegrationTests/ParameterizedQueries.cs
  src/IntegrationTests/ProjectionOrderTest.cs
  src/IntegrationTests/ValueTransformerTests.cs
  src/UnitTests/Bug/NamingConventions.cs
  src/UnitTests/IMappingExpression/IncludeMembers.cs
  src/UnitTests/Internal/DelegateFactoryTests.cs
  src/UnitTests/Internal/PrimitiveExtensionsTester.cs
  src/UnitTests/Mappers/StringDictionaryMapperTests.cs
  src/UnitTests/OpenGenerics.cs
  src/UnitTests/Projection/ConstructorTests.cs
  src/UnitTests/Projection/MembersToExpand_ExpressionArray.cs
  src/UnitTests/Projection/NullableItemsTests.cs
  src/UnitTests/Projection/ProjectionTests.cs
  src/UnitTests/Tests/TypeInfoSpecs.cs
Labels: Bug, Internal refactoring

#3500 Run lock weekly
  .github/workflows/lock.yml
Labels: Internal refactoring
