Repository AutoMapper/AutoMapper, pull requests merged in 2020-10, with the labels that each got.

#3509 Update 10.0-Upgrade-Guide.md
  docs/10.0-Upgrade-Guide.md
Labels: Documentation

#3520 NonNullableToNullable
  src/AutoMapper/QueryableExtensions/Impl/AssignableExpressionBinder.cs
  src/UnitTests/Projection/ProjectionTests.cs
Labels: Bug

#3518 Global pre and postfixes
  src/AutoMapper/ProfileMap.cs
  src/UnitTests/MemberResolution.cs
Labels: Improvement
