Repository AutoMapper/AutoMapper, pull requests merged in 2020-05, with the labels that each got.

#3403 Example for setting up DI for Catel.IoC
  docs/Dependency-injection.md
Labels: Documentation

#3400 ExactMatchNamingConvention
  src/AutoMapper/ExactMatchNamingConvention.cs
  src/UnitTests/Bug/NamingConventions.cs
Labels: Improvement

#3374 Generic value resolvers
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/TypeMap.cs
  src/UnitTests/OpenGenerics.cs
Labels: Improvement

#3387 Non generic member transformer
  src/AutoMapper/ApiCompatBaseline.txt
  src/AutoMapper/Configuration/MemberConfigurationExpression.cs
  src/AutoMapper/ValueTransformerConfiguration.cs
  src/UnitTests/ValueTransformers.cs
Labels: Improvement

#3393 Avoid collections with null values when reaching max depth
  src/AutoMapper/Execution/ExpressionBuilder.cs
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/Mappers/Internal/CollectionMapperExpressionFactory.cs
  src/UnitTests/MaxDepthTests.cs
Labels: Improvement

#3405 Improve cycle detection with inheritance
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/TypePair.cs
  src/UnitTests/BidirectionalRelationshipsWithoutPR.cs
Labels: Improvement

#3408 Update Open-Generics.md
  docs/Configuration.md
  docs/Flattening.md
  docs/Open-Generics.md
Labels: Documentation

#3401 Matching source values should override constructor parameters default…
  src/AutoMapper/AttributeExclusions.txt
  src/AutoMapper/AutoMapper.csproj
  src/AutoMapper/Configuration/CtorParamConfigurationExpression.cs
  src/AutoMapper/Configuration/MappingExpressionBase.cs
  src/AutoMapper/ConstructorParameterMap.cs
  src/AutoMapper/DefaultMemberMap.cs
  src/AutoMapper/Execution/TypeMapPlanBuilder.cs
  src/AutoMapper/PropertyMap.cs
  src/UnitTests/Constructors.cs
Labels: Improvement

#3411 EF Core; generalize constructor mapping for ProjectTo
  src/AutoMapper/ConstructorMap.cs
  src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
  src/UnitTests/Projection/ConstructorTests.cs
  src/UnitTests/Projection/MoreExplanatoryExceptionTests.cs
Labels: Improvement

#3413 Enable ForAllMaps to work with ForCtorParam
  src/AutoMapper/ApiCompatBaseline.txt
  src/AutoMapper/Configuration/MappingExpressionBase.cs
  src/AutoMapper/ProfileMap.cs
  src/UnitTests/ForAllMaps.cs
Labels: Bug

#3415 Exclude some public members from api checks
  nuget.config
  src/AutoMapper/ApiCompatBaseline.txt
  src/AutoMapper/AttributeExclusions.txt
  src/AutoMapper/AutoMapper.csproj
  src/AutoMapper/Configuration/Conventions/DefaultMember.cs
  src/AutoMapper/Configuration/Conventions/IChildMemberConfiguration.cs
  src/AutoMapper/Configuration/Conventions/IMemberConfiguration.cs
  src/AutoMapper/Configuration/Conventions/MemberConfiguration.cs
  src/AutoMapper/Configuration/Conventions/NameSplitMember.cs
  src/AutoMapper/Configuration/CtorParamConfigurationExpression.cs
  src/AutoMapper/Configuration/ITypeMapConfiguration.cs
  src/AutoMapper/Configuration/Internal/PrimitiveHelper.cs
  src/AutoMapper/ConstructorMap.cs
  src/AutoMapper/ConstructorParameterMap.cs
  src/AutoMapper/DefaultMemberMap.cs
  src/AutoMapper/Execution/DelegateFactory.cs
  src/AutoMapper/IMemberMap.cs
  src/AutoMapper/ProfileMap.cs
  src/AutoMapper/PropertyMap.cs
  src/AutoMapper/QueryableExtensions/Impl/MemberGetterExpressionResultConverter.cs
  src/AutoMapper/QueryableExtensions/Impl/MemberResolverExpressionResultConverter.cs
  src/AutoMapper/TypeMap.cs
  src/AutoMapper/TypeMapFactory.cs
Labels: Improvement
