Repository AutoMapper/AutoMapper, pull requests merged in 2020-02, with the labels that each got.

#3314 Fix .NET standard link on docs homepage
  docs/index.rst
Labels: Documentation

#3296 Consider ForCtorParam->MapFrom when projecting
  src/AutoMapper/ApiCompatBaseline.txt
  src/AutoMapper/AutoMapper.csproj
  src/AutoMapper/ConstructorMap.cs
  src/AutoMapper/QueryableExtensions/ExpressionBuilder.cs
  src/AutoMapper/QueryableExtensions/IExpressionResultConverter.cs
  src/AutoMapper/QueryableExtensions/Impl/MemberGetterExpressionResultConverter.cs
  src/AutoMapper/QueryableExtensions/Impl/MemberResolverExpressionResultConverter.cs
  src/UnitTests/IMappingExpression/ForCtorParam.cs
  src/UnitTests/Projection/BindersAndResultConverters.cs
Labels: Improvement

#3297 Enum mapping documentation
  README.md
  docs/Enum-Mapping.md
  docs/index.rst
Labels: Documentation

#3306 Update Flattening.md
  docs/Flattening.md
Labels: Documentation

#3319 Update Expression-Translation-(UseAsDataSource).md
  docs/Expression-Translation-(UseAsDataSource).md
Labels: Documentation

#3334 The source type must be assignable to the type of the transformation
  src/AutoMapper/ValueTransformerConfiguration.cs
  src/UnitTests/ValueTransformers.cs
Labels: Bug
