Repository AutoMapper/AutoMapper, pull requests merged in 2024-02, with the labels that each got.

#4382 We build for .net 6 now
  src/AutoMapper/ApiCompat/PreBuild.ps1
  src/AutoMapper/AutoMapper.csproj
Labels: Bug, Improvement

#4390 Reverted the nullable annotations
  docs/source/13.0-Upgrade-Guide.md
  src/AutoMapper/ApiCompatBaseline.txt
  src/AutoMapper/Configuration/MapperConfigurationExpression.cs
  src/AutoMapper/Mapper.cs
  src/UnitTests/NullBehavior.cs
Labels: Improvement, Documentation

#4402 Fix polymorphic mapping when some derived types have explicit mappings and others do not
  src/AutoMapper/QueryableExtensions/ProjectionBuilder.cs
  src/IntegrationTests/Inheritance/PolymorphismTests.cs
Labels: Improvement
